apiVersion: 1

contactPoints:
  - orgId: 1
    name: discord-webhook
    receivers:
      - uid: discord-webhook-receiver
        type: discord
        settings:
          url: ${DISCORD_ALERT_WEBHOOK_URL}
        disableResolveMessage: false
