server:
  port: 2333
  address: 0.0.0.0

lavalink:
  plugins:
    - dependency: "com.github.topi314.lavasrc:lavasrc-plugin:4.8.1"
      snapshot: false
  server:
    password: "youshallnotpass"
    sources:
      youtube: false
      bandcamp: true
      soundcloud: true
      twitch: true
      vimeo: true
      http: true
      local: false

plugins:
  lavasrc:
    providers:
      - "dzisrc:%ISRC%"
      - "dzsearch:%QUERY%"
    sources:
      spotify: true
      deezer: true
      applemusic: false
      yandexmusic: false
      flowerytts: false
      youtube: false
      vkmusic: false
      tidal: false
      qobuz: false
      ytdlp: false
      jiosaavn: false
    spotify:
      clientId: "${SPOTIFY_CLIENT_ID}"
      clientSecret: "${SPOTIFY_CLIENT_SECRET}"
      countryCode: "KR"
    deezer:
      masterDecryptionKey: "${DEEZER_MASTER_KEY}"
      countryCode: "KR"

logging:
  level:
    root: INFO
    lavalink: INFO
